[2025-08-01 08:29:30,932] INFO in app: ==================================================
[2025-08-01 08:29:30,955] INFO in app: Application logging initialized successfully
[2025-08-01 08:29:30,959] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 08:29:30,963] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 08:29:30,965] INFO in app: System encoding: utf-8
[2025-08-01 08:29:30,971] INFO in app: ==================================================
[2025-08-01 08:29:54,741] INFO in app: ==================================================
[2025-08-01 08:29:54,749] INFO in app: Application logging initialized successfully
[2025-08-01 08:29:54,787] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 08:29:54,791] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 08:29:54,795] INFO in app: System encoding: utf-8
[2025-08-01 08:29:54,798] INFO in app: ==================================================
[2025-08-01 08:30:03,632] INFO in app: ==================================================
[2025-08-01 08:30:03,639] INFO in app: Application logging initialized successfully
[2025-08-01 08:30:03,641] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 08:30:03,643] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 08:30:03,645] INFO in app: System encoding: utf-8
[2025-08-01 08:30:03,650] INFO in app: ==================================================
[2025-08-01 08:30:08,033] INFO in app: ==================================================
[2025-08-01 08:30:08,039] INFO in app: Application logging initialized successfully
[2025-08-01 08:30:08,041] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 08:30:08,043] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 08:30:08,044] INFO in app: System encoding: utf-8
[2025-08-01 08:30:08,046] INFO in app: ==================================================
[2025-08-01 08:31:09,981] INFO in app: ==================================================
[2025-08-01 08:31:09,987] INFO in app: Application logging initialized successfully
[2025-08-01 08:31:09,990] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 08:31:09,992] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 08:31:09,994] INFO in app: System encoding: utf-8
[2025-08-01 08:31:09,998] INFO in app: ==================================================
[2025-08-01 08:31:15,119] INFO in app: ==================================================
[2025-08-01 08:31:15,127] INFO in app: Application logging initialized successfully
[2025-08-01 08:31:15,129] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 08:31:15,131] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 08:31:15,140] INFO in app: System encoding: utf-8
[2025-08-01 08:31:15,142] INFO in app: ==================================================
[2025-08-01 08:48:12,813] INFO in app: ==================================================
[2025-08-01 08:48:12,829] INFO in app: Application logging initialized successfully
[2025-08-01 08:48:12,834] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 08:48:12,837] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 08:48:12,840] INFO in app: System encoding: utf-8
[2025-08-01 08:48:12,842] INFO in app: ==================================================
[2025-08-01 08:48:22,016] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 08:48:22,061] INFO in app: Found 7 loans for customer 202507000001
[2025-08-01 08:48:24,182] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 08:48:24,204] INFO in app: Found 7 loans for customer 202507000001
[2025-08-01 08:48:53,856] INFO in app: [TOPUP] Submit route hit for loan 8
[2025-08-01 08:48:53,980] INFO in app: [124000008] Top-up payment → top_up_interest: 151867.92, principal: 0.0
[2025-08-01 08:48:53,985] INFO in app: [124000008] Loan marked as closed after top-up payment.
[2025-08-01 08:48:54,164] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 08:48:54,182] INFO in app: Found 8 loans for customer 202507000001
[2025-08-01 08:59:35,838] INFO in app: ==================================================
[2025-08-01 08:59:35,848] INFO in app: Application logging initialized successfully
[2025-08-01 08:59:35,850] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 08:59:35,852] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 08:59:35,854] INFO in app: System encoding: utf-8
[2025-08-01 08:59:35,857] INFO in app: ==================================================
[2025-08-01 09:00:07,609] INFO in app: ==================================================
[2025-08-01 09:00:07,622] INFO in app: Application logging initialized successfully
[2025-08-01 09:00:07,627] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 09:00:07,631] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 09:00:07,636] INFO in app: System encoding: utf-8
[2025-08-01 09:00:07,646] INFO in app: ==================================================
[2025-08-01 09:00:47,525] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 09:00:47,565] INFO in app: Found 8 loans for customer 202507000001
[2025-08-01 09:00:53,938] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 09:00:53,961] INFO in app: Found 3 loans for customer 202507000002
[2025-08-01 09:00:56,713] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 09:00:56,737] INFO in app: Found 3 loans for customer 202507000002
[2025-08-01 09:01:42,356] INFO in app: [TOPUP] Submit route hit for loan 7
[2025-08-01 09:01:42,462] INFO in app: [124000007] Top-up payment → principal: 4026000.0, top-up interest: 416621.21
[2025-08-01 09:01:42,465] INFO in app: [124000007] Loan marked as closed after top-up.
[2025-08-01 09:01:42,647] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 09:01:42,657] INFO in app: Found 4 loans for customer 202507000002
[2025-08-01 09:10:14,588] INFO in app: ==================================================
[2025-08-01 09:10:14,596] INFO in app: Application logging initialized successfully
[2025-08-01 09:10:14,600] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 09:10:14,602] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 09:10:14,605] INFO in app: System encoding: utf-8
[2025-08-01 09:10:14,607] INFO in app: ==================================================
[2025-08-01 09:10:29,586] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 09:10:29,631] INFO in app: Found 8 loans for customer 202507000001
[2025-08-01 09:10:31,296] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 09:10:31,308] INFO in app: Found 8 loans for customer 202507000001
[2025-08-01 09:11:00,508] INFO in app: [TOPUP] Submit route hit for loan 5
[2025-08-01 09:11:00,675] INFO in app: [136000005] Top-up payment → principal: 2474600.0, top-up interest: 249103.71
[2025-08-01 09:11:00,679] INFO in app: [136000005] Loan marked as closed after top-up.
[2025-08-01 09:11:00,795] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 09:11:00,801] INFO in app: Found 9 loans for customer 202507000001
[2025-08-01 09:11:11,238] INFO in app: [DISBURSEMENT] Loan #112000001 | Top-up of: None | Cash to Client: 1000000.0
[2025-08-01 09:11:11,242] INFO in app: [DISBURSEMENT] Loan #136000002 | Top-up of: None | Cash to Client: 1500000.0
[2025-08-01 09:11:11,250] INFO in app: [DISBURSEMENT] Loan #124000003 | Top-up of: None | Cash to Client: 1200000.0
[2025-08-01 09:11:11,258] INFO in app: [DISBURSEMENT] Loan #118000004 | Top-up of: 1 | Cash to Client: 738713.64
[2025-08-01 09:11:11,268] INFO in app: [DISBURSEMENT] Loan #136000005 | Top-up of: 4 | Cash to Client: 1276296.29
[2025-08-01 09:11:11,276] INFO in app: [DISBURSEMENT] Loan #136000006 | Top-up of: 2 | Cash to Client: 777034.17
[2025-08-01 09:11:11,279] INFO in app: [DISBURSEMENT] Loan #124000007 | Top-up of: 6 | Cash to Client: 3557378.79
[2025-08-01 09:11:11,282] INFO in app: [DISBURSEMENT] Loan #124000008 | Top-up of: 3 | Cash to Client: 2360732.08
[2025-08-01 09:11:11,289] INFO in app: [DISBURSEMENT] Loan #103000009 | Top-up of: None | Cash to Client: 1200000.0
[2025-08-01 09:11:11,292] INFO in app: [DISBURSEMENT] Loan #124000010 | Top-up of: 9 | Cash to Client: 2508800.38
[2025-08-01 09:11:11,298] INFO in app: [DISBURSEMENT] Loan #103000011 | Top-up of: 8 | Cash to Client: 3543488.33
[2025-08-01 09:11:11,301] INFO in app: [DISBURSEMENT] Loan #124000012 | Top-up of: 7 | Cash to Client: 4090282.96
[2025-08-01 09:11:11,310] INFO in app: [DISBURSEMENT] Loan #136000013 | Top-up of: 5 | Cash to Client: 4077608.54
[2025-08-01 09:11:17,520] ERROR in app: [DISBURSE] Error for loan 112000001: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:17,527] ERROR in app: [DISBURSE] Error for loan 136000002: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:17,554] ERROR in app: [DISBURSE] Error for loan 124000003: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:17,624] ERROR in app: [DISBURSE] Error for loan 118000004: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:17,734] ERROR in app: [DISBURSE] Error for loan 136000005: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:17,813] ERROR in app: [DISBURSE] Error for loan 136000006: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:17,830] ERROR in app: [DISBURSE] Error for loan 124000007: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:17,840] ERROR in app: [DISBURSE] Error for loan 124000008: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:17,853] ERROR in app: [DISBURSE] Error for loan 103000009: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:17,862] ERROR in app: [DISBURSE] Error for loan 124000010: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:17,873] ERROR in app: [DISBURSE] Error for loan 103000011: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:17,881] ERROR in app: [DISBURSE] Error for loan 124000012: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:17,888] ERROR in app: [DISBURSE] Error for loan 136000013: 'LoanApplication' object has no attribute 'repayment_schedule'
[2025-08-01 09:11:19,644] INFO in app: [DISBURSEMENT] Loan #112000001 | Top-up of: None | Cash to Client: 1000000.0
[2025-08-01 09:11:19,646] INFO in app: [DISBURSEMENT] Loan #136000002 | Top-up of: None | Cash to Client: 1500000.0
[2025-08-01 09:11:19,649] INFO in app: [DISBURSEMENT] Loan #124000003 | Top-up of: None | Cash to Client: 1200000.0
[2025-08-01 09:11:19,652] INFO in app: [DISBURSEMENT] Loan #118000004 | Top-up of: 1 | Cash to Client: 738713.64
[2025-08-01 09:11:19,655] INFO in app: [DISBURSEMENT] Loan #136000005 | Top-up of: 4 | Cash to Client: 1276296.29
[2025-08-01 09:11:19,657] INFO in app: [DISBURSEMENT] Loan #136000006 | Top-up of: 2 | Cash to Client: 777034.17
[2025-08-01 09:11:19,665] INFO in app: [DISBURSEMENT] Loan #124000007 | Top-up of: 6 | Cash to Client: 3557378.79
[2025-08-01 09:11:19,668] INFO in app: [DISBURSEMENT] Loan #124000008 | Top-up of: 3 | Cash to Client: 2360732.08
[2025-08-01 09:11:19,671] INFO in app: [DISBURSEMENT] Loan #103000009 | Top-up of: None | Cash to Client: 1200000.0
[2025-08-01 09:11:19,675] INFO in app: [DISBURSEMENT] Loan #124000010 | Top-up of: 9 | Cash to Client: 2508800.38
[2025-08-01 09:11:19,678] INFO in app: [DISBURSEMENT] Loan #103000011 | Top-up of: 8 | Cash to Client: 3543488.33
[2025-08-01 09:11:19,694] INFO in app: [DISBURSEMENT] Loan #124000012 | Top-up of: 7 | Cash to Client: 4090282.96
[2025-08-01 09:11:19,707] INFO in app: [DISBURSEMENT] Loan #136000013 | Top-up of: 5 | Cash to Client: 4077608.54
[2025-08-01 09:25:18,254] INFO in app: ==================================================
[2025-08-01 09:25:18,260] INFO in app: Application logging initialized successfully
[2025-08-01 09:25:18,262] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 09:25:18,264] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 09:25:18,267] INFO in app: System encoding: utf-8
[2025-08-01 09:25:18,270] INFO in app: ==================================================
[2025-08-01 09:25:24,482] INFO in app: ==================================================
[2025-08-01 09:25:24,499] INFO in app: Application logging initialized successfully
[2025-08-01 09:25:24,506] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 09:25:24,512] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 09:25:24,520] INFO in app: System encoding: utf-8
[2025-08-01 09:25:24,524] INFO in app: ==================================================
[2025-08-01 09:25:29,384] INFO in app: ==================================================
[2025-08-01 09:25:29,392] INFO in app: Application logging initialized successfully
[2025-08-01 09:25:29,395] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 09:25:29,397] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 09:25:29,402] INFO in app: System encoding: utf-8
[2025-08-01 09:25:29,420] INFO in app: ==================================================
[2025-08-01 09:26:30,688] INFO in app: ==================================================
[2025-08-01 09:26:30,697] INFO in app: Application logging initialized successfully
[2025-08-01 09:26:30,700] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 09:26:30,703] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 09:26:30,708] INFO in app: System encoding: utf-8
[2025-08-01 09:26:30,712] INFO in app: ==================================================
[2025-08-01 09:26:36,715] INFO in app: ==================================================
[2025-08-01 09:26:36,725] INFO in app: Application logging initialized successfully
[2025-08-01 09:26:36,727] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 09:26:36,731] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 09:26:36,733] INFO in app: System encoding: utf-8
[2025-08-01 09:26:36,734] INFO in app: ==================================================
[2025-08-01 10:11:01,625] INFO in app: ==================================================
[2025-08-01 10:11:01,645] INFO in app: Application logging initialized successfully
[2025-08-01 10:11:01,659] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 10:11:01,663] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 10:11:01,668] INFO in app: System encoding: utf-8
[2025-08-01 10:11:01,671] INFO in app: ==================================================
[2025-08-01 10:11:15,292] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 10:11:15,329] INFO in app: Found 4 loans for customer 202507000002
[2025-08-01 10:11:25,731] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 10:11:25,752] INFO in app: Found 4 loans for customer 202507000002
[2025-08-01 10:12:07,520] INFO in app: [TOPUP] Submit route hit for loan 12
[2025-08-01 10:12:07,725] INFO in app: [124000012] Top-up payment → principal: 9899000.0, top-up interest: 1010717.04
[2025-08-01 10:12:07,817] INFO in app: [124000012] Loan marked as closed after top-up.
[2025-08-01 10:12:07,958] INFO in app: Found 6 agents and 5 team leaders
[2025-08-01 10:12:07,967] INFO in app: Found 5 loans for customer 202507000002
[2025-08-01 10:21:46,568] INFO in app: ==================================================
[2025-08-01 10:21:46,651] INFO in app: Application logging initialized successfully
[2025-08-01 10:21:46,664] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 10:21:46,669] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 10:21:46,679] INFO in app: System encoding: utf-8
[2025-08-01 10:21:46,682] INFO in app: ==================================================
[2025-08-01 10:22:29,513] INFO in app: ==================================================
[2025-08-01 10:22:29,531] INFO in app: Application logging initialized successfully
[2025-08-01 10:22:29,537] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 10:22:29,540] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 10:22:29,542] INFO in app: System encoding: utf-8
[2025-08-01 10:22:29,547] INFO in app: ==================================================
[2025-08-01 10:23:52,734] INFO in app: ==================================================
[2025-08-01 10:23:52,768] INFO in app: Application logging initialized successfully
[2025-08-01 10:23:52,774] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 10:23:52,788] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 10:23:52,793] INFO in app: System encoding: utf-8
[2025-08-01 10:23:52,814] INFO in app: ==================================================
[2025-08-01 10:29:34,912] INFO in app: ==================================================
[2025-08-01 10:29:34,929] INFO in app: Application logging initialized successfully
[2025-08-01 10:29:34,937] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 10:29:34,953] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 10:29:34,963] INFO in app: System encoding: utf-8
[2025-08-01 10:29:34,979] INFO in app: ==================================================
[2025-08-01 10:53:30,203] INFO in app: ==================================================
[2025-08-01 10:53:30,213] INFO in app: Application logging initialized successfully
[2025-08-01 10:53:30,216] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 10:53:30,220] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 10:53:30,223] INFO in app: System encoding: utf-8
[2025-08-01 10:53:30,226] INFO in app: ==================================================
[2025-08-01 10:53:34,811] ERROR in app: Exception on /dashboard/sales [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 7542, in sales_dashboard
    total_loan = sum(loan.amount_requested or 0 for loan in loans)
  File "C:\Users\pc\loan-app\app.py", line 7542, in <genexpr>
    total_loan = sum(loan.amount_requested or 0 for loan in loans)
                     ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LoanApplication' object has no attribute 'amount_requested'
[2025-08-01 10:55:32,116] INFO in app: ==================================================
[2025-08-01 10:55:32,125] INFO in app: Application logging initialized successfully
[2025-08-01 10:55:32,129] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 10:55:32,131] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 10:55:32,134] INFO in app: System encoding: utf-8
[2025-08-01 10:55:32,141] INFO in app: ==================================================
[2025-08-01 10:57:09,397] INFO in app: ==================================================
[2025-08-01 10:57:09,405] INFO in app: Application logging initialized successfully
[2025-08-01 10:57:09,413] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 10:57:09,419] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 10:57:09,423] INFO in app: System encoding: utf-8
[2025-08-01 10:57:09,426] INFO in app: ==================================================
[2025-08-01 15:47:09,941] INFO in app: ==================================================
[2025-08-01 15:47:10,027] INFO in app: Application logging initialized successfully
[2025-08-01 15:47:10,030] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 15:47:10,031] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 15:47:10,033] INFO in app: System encoding: utf-8
[2025-08-01 15:47:10,037] INFO in app: ==================================================
[2025-08-01 15:47:18,378] INFO in app: ==================================================
[2025-08-01 15:47:18,385] INFO in app: Application logging initialized successfully
[2025-08-01 15:47:18,388] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 15:47:18,393] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 15:47:18,398] INFO in app: System encoding: utf-8
[2025-08-01 15:47:18,401] INFO in app: ==================================================
[2025-08-01 15:51:12,928] INFO in app: ==================================================
[2025-08-01 15:51:12,937] INFO in app: Application logging initialized successfully
[2025-08-01 15:51:12,938] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-01 15:51:12,939] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-01 15:51:12,941] INFO in app: System encoding: utf-8
[2025-08-01 15:51:12,943] INFO in app: ==================================================
[2025-08-02 07:57:56,503] INFO in app: ==================================================
[2025-08-02 07:57:56,578] INFO in app: Application logging initialized successfully
[2025-08-02 07:57:56,580] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 07:57:56,582] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 07:57:56,583] INFO in app: System encoding: utf-8
[2025-08-02 07:57:56,589] INFO in app: ==================================================
[2025-08-02 08:08:26,744] INFO in app: ==================================================
[2025-08-02 08:08:26,751] INFO in app: Application logging initialized successfully
[2025-08-02 08:08:26,753] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 08:08:26,756] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 08:08:26,758] INFO in app: System encoding: utf-8
[2025-08-02 08:08:26,761] INFO in app: ==================================================
[2025-08-02 08:09:58,285] ERROR in app: Exception on /dashboard/sales [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 7563, in sales_dashboard
    return render_template(
        "dashboard/sales_dashboard.html",
    ...<5 lines>...
        notif=notif
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\pc\loan-app\templates\dashboard\sales_dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\pc\loan-app\templates\base.html", line 177, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\templates\dashboard\sales_dashboard.html", line 17, in block 'content'
    {% include "dashboard/_tabs.html" with context %}
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\templates\dashboard\_tabs.html", line 6, in top-level template code
    <a class="nav-link {% if active_tab == 'team' %}active{% endif %}" href="{{ url_for('team_leader_dashboard') }}">Team Leader</a>
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'team_leader_dashboard'. Did you mean 'sales_dashboard' instead?
[2025-08-02 08:25:43,647] INFO in app: ==================================================
[2025-08-02 08:25:43,654] INFO in app: Application logging initialized successfully
[2025-08-02 08:25:43,657] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 08:25:43,658] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 08:25:43,659] INFO in app: System encoding: utf-8
[2025-08-02 08:25:43,661] INFO in app: ==================================================
[2025-08-02 08:25:47,916] ERROR in app: Exception on /dashboard/sales [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 7563, in sales_dashboard
    return render_template(
        "dashboard/sales_dashboard.html",
    ...<5 lines>...
        notif=notif
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\pc\loan-app\templates\dashboard\sales_dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\pc\loan-app\templates\base.html", line 177, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\templates\dashboard\sales_dashboard.html", line 20, in block 'content'
    <a href="{{ url_for('add_team_with_agents') }}" class="btn btn-success" aria-label="Add new team and agents">
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'add_team_with_agents'. Did you mean 'delete_test_payments' instead?
[2025-08-02 10:40:40,190] INFO in app: ==================================================
[2025-08-02 10:40:40,216] INFO in app: Application logging initialized successfully
[2025-08-02 10:40:40,220] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 10:40:40,244] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 10:40:40,251] INFO in app: System encoding: utf-8
[2025-08-02 10:40:40,267] INFO in app: ==================================================
[2025-08-02 11:48:25,279] INFO in app: ==================================================
[2025-08-02 11:48:25,285] INFO in app: Application logging initialized successfully
[2025-08-02 11:48:25,286] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 11:48:25,287] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 11:48:25,288] INFO in app: System encoding: utf-8
[2025-08-02 11:48:25,289] INFO in app: ==================================================
[2025-08-02 12:04:33,882] INFO in app: ==================================================
[2025-08-02 12:04:33,888] INFO in app: Application logging initialized successfully
[2025-08-02 12:04:33,891] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 12:04:33,893] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 12:04:33,895] INFO in app: System encoding: utf-8
[2025-08-02 12:04:33,902] INFO in app: ==================================================
[2025-08-02 12:05:13,191] INFO in app: ==================================================
[2025-08-02 12:05:13,198] INFO in app: Application logging initialized successfully
[2025-08-02 12:05:13,200] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 12:05:13,204] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 12:05:13,206] INFO in app: System encoding: utf-8
[2025-08-02 12:05:13,211] INFO in app: ==================================================
[2025-08-02 12:05:25,269] INFO in app: ==================================================
[2025-08-02 12:05:25,275] INFO in app: Application logging initialized successfully
[2025-08-02 12:05:25,277] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 12:05:25,279] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 12:05:25,286] INFO in app: System encoding: utf-8
[2025-08-02 12:05:25,288] INFO in app: ==================================================
[2025-08-02 12:05:33,185] INFO in app: ==================================================
[2025-08-02 12:05:33,191] INFO in app: Application logging initialized successfully
[2025-08-02 12:05:33,193] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 12:05:33,199] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 12:05:33,205] INFO in app: System encoding: utf-8
[2025-08-02 12:05:33,206] INFO in app: ==================================================
[2025-08-02 12:05:38,581] INFO in app: ==================================================
[2025-08-02 12:05:38,587] INFO in app: Application logging initialized successfully
[2025-08-02 12:05:38,589] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 12:05:38,590] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 12:05:38,592] INFO in app: System encoding: utf-8
[2025-08-02 12:05:38,597] INFO in app: ==================================================
[2025-08-02 12:12:42,824] INFO in app: ==================================================
[2025-08-02 12:12:42,838] INFO in app: Application logging initialized successfully
[2025-08-02 12:12:42,842] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 12:12:42,846] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 12:12:42,848] INFO in app: System encoding: utf-8
[2025-08-02 12:12:42,859] INFO in app: ==================================================
[2025-08-02 12:12:57,606] INFO in app: ==================================================
[2025-08-02 12:12:57,617] INFO in app: Application logging initialized successfully
[2025-08-02 12:12:57,618] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 12:12:57,619] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 12:12:57,620] INFO in app: System encoding: utf-8
[2025-08-02 12:12:57,621] INFO in app: ==================================================
[2025-08-02 13:10:11,027] INFO in app: ==================================================
[2025-08-02 13:10:11,037] INFO in app: Application logging initialized successfully
[2025-08-02 13:10:11,040] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 13:10:11,042] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 13:10:11,046] INFO in app: System encoding: utf-8
[2025-08-02 13:10:11,053] INFO in app: ==================================================
[2025-08-02 13:18:54,916] INFO in app: ==================================================
[2025-08-02 13:18:54,928] INFO in app: Application logging initialized successfully
[2025-08-02 13:18:54,935] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 13:18:54,946] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 13:18:54,951] INFO in app: System encoding: utf-8
[2025-08-02 13:18:54,992] INFO in app: ==================================================
[2025-08-02 13:27:04,862] INFO in app: ==================================================
[2025-08-02 13:27:04,873] INFO in app: Application logging initialized successfully
[2025-08-02 13:27:04,874] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 13:27:04,878] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 13:27:04,880] INFO in app: System encoding: utf-8
[2025-08-02 13:27:04,882] INFO in app: ==================================================
[2025-08-02 16:12:42,998] INFO in app: ==================================================
[2025-08-02 16:12:43,106] INFO in app: Application logging initialized successfully
[2025-08-02 16:12:43,108] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-02 16:12:43,110] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-02 16:12:43,118] INFO in app: System encoding: utf-8
[2025-08-02 16:12:43,123] INFO in app: ==================================================
[2025-08-03 04:17:17,280] INFO in app: ==================================================
[2025-08-03 04:17:17,430] INFO in app: Application logging initialized successfully
[2025-08-03 04:17:17,433] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 04:17:17,436] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 04:17:17,439] INFO in app: System encoding: utf-8
[2025-08-03 04:17:17,443] INFO in app: ==================================================
[2025-08-03 04:18:27,689] INFO in app: ==================================================
[2025-08-03 04:18:27,700] INFO in app: Application logging initialized successfully
[2025-08-03 04:18:27,706] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 04:18:27,710] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 04:18:27,717] INFO in app: System encoding: utf-8
[2025-08-03 04:18:27,724] INFO in app: ==================================================
[2025-08-03 04:33:32,809] INFO in app: ==================================================
[2025-08-03 04:33:32,820] INFO in app: Application logging initialized successfully
[2025-08-03 04:33:32,824] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 04:33:32,826] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 04:33:32,830] INFO in app: System encoding: utf-8
[2025-08-03 04:33:32,833] INFO in app: ==================================================
[2025-08-03 04:39:02,580] INFO in app: ==================================================
[2025-08-03 04:39:02,594] INFO in app: Application logging initialized successfully
[2025-08-03 04:39:02,598] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 04:39:02,601] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 04:39:02,606] INFO in app: System encoding: utf-8
[2025-08-03 04:39:02,615] INFO in app: ==================================================
[2025-08-03 04:45:36,061] INFO in app: ==================================================
[2025-08-03 04:45:36,071] INFO in app: Application logging initialized successfully
[2025-08-03 04:45:36,074] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 04:45:36,076] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 04:45:36,082] INFO in app: System encoding: utf-8
[2025-08-03 04:45:36,085] INFO in app: ==================================================
[2025-08-03 04:46:58,872] INFO in app: ==================================================
[2025-08-03 04:46:58,880] INFO in app: Application logging initialized successfully
[2025-08-03 04:46:58,885] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 04:46:58,887] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 04:46:58,890] INFO in app: System encoding: utf-8
[2025-08-03 04:46:58,892] INFO in app: ==================================================
[2025-08-03 04:57:47,555] INFO in app: ==================================================
[2025-08-03 04:57:47,614] INFO in app: Application logging initialized successfully
[2025-08-03 04:57:47,616] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 04:57:47,617] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 04:57:47,618] INFO in app: System encoding: utf-8
[2025-08-03 04:57:47,619] INFO in app: ==================================================
[2025-08-03 04:57:47,711] INFO in app: ==================================================
[2025-08-03 04:57:47,711] INFO in app: ==================================================
[2025-08-03 04:57:47,716] INFO in app: Application logging initialized successfully
[2025-08-03 04:57:47,716] INFO in app: Application logging initialized successfully
[2025-08-03 04:57:47,718] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 04:57:47,718] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 04:57:47,720] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 04:57:47,720] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 04:57:47,722] INFO in app: System encoding: utf-8
[2025-08-03 04:57:47,722] INFO in app: System encoding: utf-8
[2025-08-03 04:57:47,724] INFO in app: ==================================================
[2025-08-03 04:57:47,724] INFO in app: ==================================================
[2025-08-03 05:02:46,779] INFO in app: ==================================================
[2025-08-03 05:02:46,786] INFO in app: Application logging initialized successfully
[2025-08-03 05:02:46,787] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:02:46,788] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:02:46,789] INFO in app: System encoding: utf-8
[2025-08-03 05:02:46,790] INFO in app: ==================================================
[2025-08-03 05:02:46,824] INFO in app: ==================================================
[2025-08-03 05:02:46,824] INFO in app: ==================================================
[2025-08-03 05:02:46,830] INFO in app: Application logging initialized successfully
[2025-08-03 05:02:46,830] INFO in app: Application logging initialized successfully
[2025-08-03 05:02:46,834] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:02:46,834] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:02:46,837] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:02:46,837] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:02:46,839] INFO in app: System encoding: utf-8
[2025-08-03 05:02:46,839] INFO in app: System encoding: utf-8
[2025-08-03 05:02:46,841] INFO in app: ==================================================
[2025-08-03 05:02:46,841] INFO in app: ==================================================
[2025-08-03 05:08:34,905] INFO in app: ==================================================
[2025-08-03 05:08:34,988] INFO in app: Application logging initialized successfully
[2025-08-03 05:08:34,989] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:08:34,991] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:08:34,998] INFO in app: System encoding: utf-8
[2025-08-03 05:08:34,999] INFO in app: ==================================================
[2025-08-03 05:08:50,393] INFO in app: ==================================================
[2025-08-03 05:08:50,401] INFO in app: Application logging initialized successfully
[2025-08-03 05:08:50,402] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:08:50,403] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:08:50,405] INFO in app: System encoding: utf-8
[2025-08-03 05:08:50,408] INFO in app: ==================================================
[2025-08-03 05:08:50,438] INFO in app: ==================================================
[2025-08-03 05:08:50,438] INFO in app: ==================================================
[2025-08-03 05:08:50,442] INFO in app: Application logging initialized successfully
[2025-08-03 05:08:50,442] INFO in app: Application logging initialized successfully
[2025-08-03 05:08:50,445] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:08:50,445] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:08:50,447] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:08:50,447] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:08:50,449] INFO in app: System encoding: utf-8
[2025-08-03 05:08:50,449] INFO in app: System encoding: utf-8
[2025-08-03 05:08:50,451] INFO in app: ==================================================
[2025-08-03 05:08:50,451] INFO in app: ==================================================
[2025-08-03 05:09:32,022] INFO in app: ==================================================
[2025-08-03 05:09:32,161] INFO in app: Application logging initialized successfully
[2025-08-03 05:09:32,185] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:09:32,187] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:09:32,189] INFO in app: System encoding: utf-8
[2025-08-03 05:09:32,197] INFO in app: ==================================================
[2025-08-03 05:09:40,929] INFO in app: ==================================================
[2025-08-03 05:09:40,942] INFO in app: Application logging initialized successfully
[2025-08-03 05:09:40,948] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:09:40,950] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:09:40,957] INFO in app: System encoding: utf-8
[2025-08-03 05:09:40,961] INFO in app: ==================================================
[2025-08-03 05:09:58,938] INFO in app: ==================================================
[2025-08-03 05:09:58,945] INFO in app: Application logging initialized successfully
[2025-08-03 05:09:58,946] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:09:58,947] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:09:58,950] INFO in app: System encoding: utf-8
[2025-08-03 05:09:58,953] INFO in app: ==================================================
[2025-08-03 05:09:58,984] INFO in app: ==================================================
[2025-08-03 05:09:58,984] INFO in app: ==================================================
[2025-08-03 05:09:58,988] INFO in app: Application logging initialized successfully
[2025-08-03 05:09:58,988] INFO in app: Application logging initialized successfully
[2025-08-03 05:09:58,992] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:09:58,992] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:09:58,994] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:09:58,994] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:09:58,996] INFO in app: System encoding: utf-8
[2025-08-03 05:09:58,996] INFO in app: System encoding: utf-8
[2025-08-03 05:09:59,000] INFO in app: ==================================================
[2025-08-03 05:09:59,000] INFO in app: ==================================================
[2025-08-03 05:23:40,503] INFO in app: ==================================================
[2025-08-03 05:23:40,509] INFO in app: Application logging initialized successfully
[2025-08-03 05:23:40,511] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:23:40,513] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:23:40,515] INFO in app: System encoding: utf-8
[2025-08-03 05:23:40,519] INFO in app: ==================================================
[2025-08-03 05:23:53,540] INFO in app: ==================================================
[2025-08-03 05:23:53,547] INFO in app: Application logging initialized successfully
[2025-08-03 05:23:53,548] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:23:53,551] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:23:53,553] INFO in app: System encoding: utf-8
[2025-08-03 05:23:53,554] INFO in app: ==================================================
[2025-08-03 05:23:53,584] INFO in app: ==================================================
[2025-08-03 05:23:53,584] INFO in app: ==================================================
[2025-08-03 05:23:53,589] INFO in app: Application logging initialized successfully
[2025-08-03 05:23:53,589] INFO in app: Application logging initialized successfully
[2025-08-03 05:23:53,591] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:23:53,591] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:23:53,593] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:23:53,593] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:23:53,595] INFO in app: System encoding: utf-8
[2025-08-03 05:23:53,595] INFO in app: System encoding: utf-8
[2025-08-03 05:23:53,597] INFO in app: ==================================================
[2025-08-03 05:23:53,597] INFO in app: ==================================================
[2025-08-03 05:31:38,683] INFO in app: ==================================================
[2025-08-03 05:31:38,693] INFO in app: Application logging initialized successfully
[2025-08-03 05:31:38,695] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:31:38,714] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:31:38,716] INFO in app: System encoding: utf-8
[2025-08-03 05:31:38,718] INFO in app: ==================================================
[2025-08-03 05:31:51,045] INFO in app: ==================================================
[2025-08-03 05:31:51,053] INFO in app: Application logging initialized successfully
[2025-08-03 05:31:51,056] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:31:51,059] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:31:51,060] INFO in app: System encoding: utf-8
[2025-08-03 05:31:51,063] INFO in app: ==================================================
[2025-08-03 05:31:51,100] INFO in app: ==================================================
[2025-08-03 05:31:51,100] INFO in app: ==================================================
[2025-08-03 05:31:51,104] INFO in app: Application logging initialized successfully
[2025-08-03 05:31:51,104] INFO in app: Application logging initialized successfully
[2025-08-03 05:31:51,109] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:31:51,109] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:31:51,112] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:31:51,112] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:31:51,114] INFO in app: System encoding: utf-8
[2025-08-03 05:31:51,114] INFO in app: System encoding: utf-8
[2025-08-03 05:31:51,117] INFO in app: ==================================================
[2025-08-03 05:31:51,117] INFO in app: ==================================================
[2025-08-03 05:32:53,036] INFO in app: ==================================================
[2025-08-03 05:32:53,044] INFO in app: Application logging initialized successfully
[2025-08-03 05:32:53,048] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:32:53,050] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:32:53,054] INFO in app: System encoding: utf-8
[2025-08-03 05:32:53,059] INFO in app: ==================================================
[2025-08-03 05:32:57,678] INFO in app: ==================================================
[2025-08-03 05:32:57,687] INFO in app: Application logging initialized successfully
[2025-08-03 05:32:57,688] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:32:57,690] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:32:57,691] INFO in app: System encoding: utf-8
[2025-08-03 05:32:57,693] INFO in app: ==================================================
[2025-08-03 05:32:57,740] INFO in app: ==================================================
[2025-08-03 05:32:57,740] INFO in app: ==================================================
[2025-08-03 05:32:57,751] INFO in app: Application logging initialized successfully
[2025-08-03 05:32:57,751] INFO in app: Application logging initialized successfully
[2025-08-03 05:32:57,757] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:32:57,757] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:32:57,759] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:32:57,759] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:32:57,761] INFO in app: System encoding: utf-8
[2025-08-03 05:32:57,761] INFO in app: System encoding: utf-8
[2025-08-03 05:32:57,763] INFO in app: ==================================================
[2025-08-03 05:32:57,763] INFO in app: ==================================================
[2025-08-03 05:37:09,898] INFO in app: ==================================================
[2025-08-03 05:37:09,905] INFO in app: Application logging initialized successfully
[2025-08-03 05:37:09,907] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:37:09,908] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:37:09,916] INFO in app: System encoding: utf-8
[2025-08-03 05:37:09,917] INFO in app: ==================================================
[2025-08-03 05:37:20,597] INFO in app: ==================================================
[2025-08-03 05:37:20,603] INFO in app: Application logging initialized successfully
[2025-08-03 05:37:20,605] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:37:20,608] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:37:20,610] INFO in app: System encoding: utf-8
[2025-08-03 05:37:20,614] INFO in app: ==================================================
[2025-08-03 05:43:08,894] INFO in app: ==================================================
[2025-08-03 05:43:08,905] INFO in app: Application logging initialized successfully
[2025-08-03 05:43:08,908] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:43:08,915] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:43:08,918] INFO in app: System encoding: utf-8
[2025-08-03 05:43:08,922] INFO in app: ==================================================
[2025-08-03 05:43:29,066] INFO in app: ==================================================
[2025-08-03 05:43:29,073] INFO in app: Application logging initialized successfully
[2025-08-03 05:43:29,074] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:43:29,076] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:43:29,077] INFO in app: System encoding: utf-8
[2025-08-03 05:43:29,079] INFO in app: ==================================================
[2025-08-03 05:43:29,111] INFO in app: ==================================================
[2025-08-03 05:43:29,111] INFO in app: ==================================================
[2025-08-03 05:43:29,114] INFO in app: Application logging initialized successfully
[2025-08-03 05:43:29,114] INFO in app: Application logging initialized successfully
[2025-08-03 05:43:29,116] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:43:29,116] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 05:43:29,118] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:43:29,118] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 05:43:29,123] INFO in app: System encoding: utf-8
[2025-08-03 05:43:29,123] INFO in app: System encoding: utf-8
[2025-08-03 05:43:29,126] INFO in app: ==================================================
[2025-08-03 05:43:29,126] INFO in app: ==================================================
[2025-08-03 06:07:01,756] INFO in app: ==================================================
[2025-08-03 06:07:01,762] INFO in app: Application logging initialized successfully
[2025-08-03 06:07:01,764] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 06:07:01,766] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 06:07:01,770] INFO in app: System encoding: utf-8
[2025-08-03 06:07:01,775] INFO in app: ==================================================
[2025-08-03 06:07:12,614] INFO in app: ==================================================
[2025-08-03 06:07:12,622] INFO in app: Application logging initialized successfully
[2025-08-03 06:07:12,625] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 06:07:12,627] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 06:07:12,629] INFO in app: System encoding: utf-8
[2025-08-03 06:07:12,633] INFO in app: ==================================================
[2025-08-03 06:07:32,425] INFO in app: ==================================================
[2025-08-03 06:07:32,432] INFO in app: Application logging initialized successfully
[2025-08-03 06:07:32,435] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 06:07:32,438] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 06:07:32,440] INFO in app: System encoding: utf-8
[2025-08-03 06:07:32,444] INFO in app: ==================================================
[2025-08-03 06:07:39,867] INFO in app: ==================================================
[2025-08-03 06:07:39,877] INFO in app: Application logging initialized successfully
[2025-08-03 06:07:39,879] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 06:07:39,881] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 06:07:39,883] INFO in app: System encoding: utf-8
[2025-08-03 06:07:39,889] INFO in app: ==================================================
[2025-08-03 06:23:18,459] INFO in app: ==================================================
[2025-08-03 06:23:18,469] INFO in app: Application logging initialized successfully
[2025-08-03 06:23:18,474] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 06:23:18,477] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 06:23:18,485] INFO in app: System encoding: utf-8
[2025-08-03 06:23:18,487] INFO in app: ==================================================
[2025-08-03 06:23:26,405] INFO in app: ==================================================
[2025-08-03 06:23:26,414] INFO in app: Application logging initialized successfully
[2025-08-03 06:23:26,418] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 06:23:26,420] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 06:23:26,425] INFO in app: System encoding: utf-8
[2025-08-03 06:23:26,428] INFO in app: ==================================================
[2025-08-03 06:33:30,741] INFO in app: ==================================================
[2025-08-03 06:33:30,754] INFO in app: Application logging initialized successfully
[2025-08-03 06:33:30,758] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 06:33:30,761] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 06:33:30,765] INFO in app: System encoding: utf-8
[2025-08-03 06:33:30,775] INFO in app: ==================================================
[2025-08-03 06:33:42,169] INFO in app: ==================================================
[2025-08-03 06:33:42,176] INFO in app: Application logging initialized successfully
[2025-08-03 06:33:42,179] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 06:33:42,181] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 06:33:42,184] INFO in app: System encoding: utf-8
[2025-08-03 06:33:42,187] INFO in app: ==================================================
[2025-08-03 06:34:57,251] INFO in app: ==================================================
[2025-08-03 06:34:57,261] INFO in app: Application logging initialized successfully
[2025-08-03 06:34:57,264] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 06:34:57,267] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 06:34:57,269] INFO in app: System encoding: utf-8
[2025-08-03 06:34:57,275] INFO in app: ==================================================
[2025-08-03 06:35:04,549] INFO in app: ==================================================
[2025-08-03 06:35:04,559] INFO in app: Application logging initialized successfully
[2025-08-03 06:35:04,561] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 06:35:04,565] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 06:35:04,568] INFO in app: System encoding: utf-8
[2025-08-03 06:35:04,573] INFO in app: ==================================================
[2025-08-03 07:21:47,924] INFO in app: ==================================================
[2025-08-03 07:21:47,935] INFO in app: Application logging initialized successfully
[2025-08-03 07:21:47,936] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 07:21:47,938] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 07:21:47,939] INFO in app: System encoding: utf-8
[2025-08-03 07:21:47,941] INFO in app: ==================================================
[2025-08-03 07:21:48,335] INFO in app: ==================================================
[2025-08-03 07:21:48,335] INFO in app: ==================================================
[2025-08-03 07:21:48,339] INFO in app: Application logging initialized successfully
[2025-08-03 07:21:48,339] INFO in app: Application logging initialized successfully
[2025-08-03 07:21:48,344] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 07:21:48,344] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 07:21:48,348] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 07:21:48,348] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 07:21:48,351] INFO in app: System encoding: utf-8
[2025-08-03 07:21:48,351] INFO in app: System encoding: utf-8
[2025-08-03 07:21:48,354] INFO in app: ==================================================
[2025-08-03 07:21:48,354] INFO in app: ==================================================
[2025-08-03 07:23:32,334] INFO in app: ==================================================
[2025-08-03 07:23:32,345] INFO in app: Application logging initialized successfully
[2025-08-03 07:23:32,348] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 07:23:32,350] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 07:23:32,356] INFO in app: System encoding: utf-8
[2025-08-03 07:23:32,359] INFO in app: ==================================================
[2025-08-03 07:23:39,780] INFO in app: ==================================================
[2025-08-03 07:23:39,794] INFO in app: Application logging initialized successfully
[2025-08-03 07:23:39,797] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 07:23:39,801] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 07:23:39,805] INFO in app: System encoding: utf-8
[2025-08-03 07:23:39,808] INFO in app: ==================================================
[2025-08-03 07:23:39,860] INFO in app: ==================================================
[2025-08-03 07:23:39,860] INFO in app: ==================================================
[2025-08-03 07:23:39,865] INFO in app: Application logging initialized successfully
[2025-08-03 07:23:39,865] INFO in app: Application logging initialized successfully
[2025-08-03 07:23:39,868] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 07:23:39,868] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 07:23:39,872] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 07:23:39,872] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 07:23:39,875] INFO in app: System encoding: utf-8
[2025-08-03 07:23:39,875] INFO in app: System encoding: utf-8
[2025-08-03 07:23:39,878] INFO in app: ==================================================
[2025-08-03 07:23:39,878] INFO in app: ==================================================
[2025-08-03 07:35:13,262] INFO in app: ==================================================
[2025-08-03 07:35:13,312] INFO in app: Application logging initialized successfully
[2025-08-03 07:35:13,321] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 07:35:13,333] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 07:35:13,340] INFO in app: System encoding: utf-8
[2025-08-03 07:35:13,348] INFO in app: ==================================================
[2025-08-03 07:41:24,933] ERROR in app: Account view error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-08-03 07:49:14,504] INFO in app: ==================================================
[2025-08-03 07:49:14,518] INFO in app: Application logging initialized successfully
[2025-08-03 07:49:14,521] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 07:49:14,524] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 07:49:14,528] INFO in app: System encoding: utf-8
[2025-08-03 07:49:14,535] INFO in app: ==================================================
[2025-08-03 07:49:42,377] ERROR in app: Exception on /register [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 552, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\pc\loan-app\app.py", line 4057, in register_customer_debug
    return render_template(
        'register_customer_debug.html',
        agents=agents,
        team_leaders=team_leaders
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\pc\loan-app\templates\register_customer_debug.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\pc\loan-app\templates\base.html", line 177, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\templates\register_customer_debug.html", line 362, in block 'content'
    {{ query_form.hidden_tag() }}
    ^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'query_form' is undefined
[2025-08-03 07:53:03,677] INFO in app: ==================================================
[2025-08-03 07:53:03,687] INFO in app: Application logging initialized successfully
[2025-08-03 07:53:03,690] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 07:53:03,693] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 07:53:03,703] INFO in app: System encoding: utf-8
[2025-08-03 07:53:03,706] INFO in app: ==================================================
[2025-08-03 07:53:17,745] ERROR in app: Exception on /register [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 552, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\pc\loan-app\app.py", line 4057, in register_customer_debug
    
    
    ...<3 lines>...
        team_leaders=team_leaders,
        ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\pc\loan-app\templates\register_customer_debug.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\pc\loan-app\templates\base.html", line 177, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\templates\register_customer_debug.html", line 362, in block 'content'
    {{ query_form.hidden_tag() }}
    ^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'query_form' is undefined
[2025-08-03 07:53:41,414] INFO in app: ==================================================
[2025-08-03 07:53:41,425] INFO in app: Application logging initialized successfully
[2025-08-03 07:53:41,432] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 07:53:41,436] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 07:53:41,445] INFO in app: System encoding: utf-8
[2025-08-03 07:53:41,448] INFO in app: ==================================================
[2025-08-03 07:53:57,561] ERROR in app: Exception on /customer/enquiry [POST]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 552, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\pc\loan-app\app.py", line 3594, in customer_enquiry
    return redirect(url_for('customer_account', employment_number=customer.employment_number or 'PLACEHOLDER', section=section))
                    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\helpers.py", line 232, in url_for
    return current_app.url_for(
           ~~~~~~~~~~~~~~~~~~~^
        endpoint,
        ^^^^^^^^^
    ...<4 lines>...
        **values,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'customer_account' with values ['employment_number', 'section']. Did you forget to specify values ['file_number']?
[2025-08-03 08:05:25,751] INFO in app: ==================================================
[2025-08-03 08:05:25,761] INFO in app: Application logging initialized successfully
[2025-08-03 08:05:25,766] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 08:05:25,769] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 08:05:25,775] INFO in app: System encoding: utf-8
[2025-08-03 08:05:25,777] INFO in app: ==================================================
[2025-08-03 08:06:07,599] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 08:06:07,654] INFO in app: Found 9 loans for customer 202507000001
[2025-08-03 08:06:12,401] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 08:06:12,412] INFO in app: Found 9 loans for customer 202507000001
[2025-08-03 08:06:46,322] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 08:06:46,339] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 08:07:07,888] ERROR in app: Exception on /process_loan/15/reject [POST]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: loan_applications.loan_state

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 4389, in process_loan
    db.session.commit()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 599, in commit
    return self._proxied.commit()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 85, in save_obj
    _emit_update_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        update,
        ^^^^^^^
    )
    ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        statement, multiparams, execution_options=execution_options
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: loan_applications.loan_state
[SQL: UPDATE loan_applications SET application_status=?, loan_state=? WHERE loan_applications.id = ?]
[parameters: ('rejected', None, 15)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2025-08-03 08:12:51,102] ERROR in app: Exception on /customer/enquiry [POST]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 552, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\pc\loan-app\app.py", line 3594, in customer_enquiry
    return redirect(url_for('customer_account', employment_number=customer.employment_number or 'PLACEHOLDER', section=section))
                    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\helpers.py", line 232, in url_for
    return current_app.url_for(
           ~~~~~~~~~~~~~~~~~~~^
        endpoint,
        ^^^^^^^^^
    ...<4 lines>...
        **values,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'customer_account' with values ['employment_number', 'section']. Did you forget to specify values ['file_number']?
[2025-08-03 08:15:51,940] INFO in app: ==================================================
[2025-08-03 08:15:51,949] INFO in app: Application logging initialized successfully
[2025-08-03 08:15:51,952] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 08:15:51,955] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 08:15:51,958] INFO in app: System encoding: utf-8
[2025-08-03 08:15:51,963] INFO in app: ==================================================
[2025-08-03 08:16:07,068] ERROR in app: Exception on /customer/enquiry [POST]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 552, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\pc\loan-app\app.py", line 3594, in customer_enquiry
    return redirect(url_for('customer_account', employment_number=customer.employment_number or 'PLACEHOLDER', section=section))
                    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\helpers.py", line 232, in url_for
    return current_app.url_for(
           ~~~~~~~~~~~~~~~~~~~^
        endpoint,
        ^^^^^^^^^
    ...<4 lines>...
        **values,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'customer_account' with values ['employment_number', 'section']. Did you forget to specify values ['file_number']?
[2025-08-03 08:16:40,865] INFO in app: ==================================================
[2025-08-03 08:16:40,874] INFO in app: Application logging initialized successfully
[2025-08-03 08:16:40,877] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 08:16:40,880] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 08:16:40,884] INFO in app: System encoding: utf-8
[2025-08-03 08:16:40,888] INFO in app: ==================================================
[2025-08-03 08:16:51,505] ERROR in app: Exception on /customer/enquiry [POST]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 552, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\pc\loan-app\app.py", line 3594, in customer_enquiry
    return redirect(url_for('customer_account', employment_number=customer.employment_number or 'PLACEHOLDER', section=section))
                    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\helpers.py", line 232, in url_for
    return current_app.url_for(
           ~~~~~~~~~~~~~~~~~~~^
        endpoint,
        ^^^^^^^^^
    ...<4 lines>...
        **values,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'customer_account' with values ['employment_number', 'section']. Did you forget to specify values ['file_number']?
[2025-08-03 14:39:46,015] INFO in app: ==================================================
[2025-08-03 14:39:46,025] INFO in app: Application logging initialized successfully
[2025-08-03 14:39:46,026] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 14:39:46,029] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 14:39:46,035] INFO in app: System encoding: utf-8
[2025-08-03 14:39:46,037] INFO in app: ==================================================
[2025-08-03 14:40:07,577] ERROR in app: Exception on /customer/enquiry [POST]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 552, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\pc\loan-app\app.py", line 3594, in customer_enquiry
    return redirect(url_for('customer_account', employment_number=customer.employment_number or 'PLACEHOLDER', section=section))
                    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\helpers.py", line 232, in url_for
    return current_app.url_for(
           ~~~~~~~~~~~~~~~~~~~^
        endpoint,
        ^^^^^^^^^
    ...<4 lines>...
        **values,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'customer_account' with values ['employment_number', 'section']. Did you forget to specify values ['file_number']?
[2025-08-03 14:45:02,909] INFO in app: ==================================================
[2025-08-03 14:45:02,915] INFO in app: Application logging initialized successfully
[2025-08-03 14:45:02,918] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 14:45:02,920] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 14:45:02,921] INFO in app: System encoding: utf-8
[2025-08-03 14:45:02,923] INFO in app: ==================================================
[2025-08-03 14:45:13,994] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:45:14,012] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:45:28,448] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:45:28,455] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:45:35,542] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:45:35,550] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:45:37,164] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:45:37,171] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:45:38,467] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:45:38,474] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:45:39,412] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:45:39,422] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:45:46,162] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:45:46,173] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:45:47,413] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:45:47,422] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:45:48,873] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:45:48,884] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:45:53,117] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:45:53,128] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:45:55,016] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:45:55,027] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:46:05,658] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:46:05,670] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:46:14,276] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:46:14,282] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:46:15,420] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:46:15,430] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:46:16,467] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:46:16,475] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:46:17,408] INFO in app: Found 6 agents and 5 team leaders
[2025-08-03 14:46:17,420] INFO in app: Found 10 loans for customer 202507000001
[2025-08-03 14:50:36,937] INFO in app: ==================================================
[2025-08-03 14:50:36,945] INFO in app: Application logging initialized successfully
[2025-08-03 14:50:36,948] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 14:50:36,950] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 14:50:36,953] INFO in app: System encoding: utf-8
[2025-08-03 14:50:36,956] INFO in app: ==================================================
[2025-08-03 14:50:46,065] INFO in app: ==================================================
[2025-08-03 14:50:46,078] INFO in app: Application logging initialized successfully
[2025-08-03 14:50:46,082] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 14:50:46,089] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 14:50:46,092] INFO in app: System encoding: utf-8
[2025-08-03 14:50:46,094] INFO in app: ==================================================
[2025-08-03 14:56:52,550] INFO in app: ==================================================
[2025-08-03 14:56:52,558] INFO in app: Application logging initialized successfully
[2025-08-03 14:56:52,562] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 14:56:52,568] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 14:56:52,571] INFO in app: System encoding: utf-8
[2025-08-03 14:56:52,573] INFO in app: ==================================================
[2025-08-03 15:52:50,751] INFO in app: ==================================================
[2025-08-03 15:52:50,881] INFO in app: Application logging initialized successfully
[2025-08-03 15:52:50,886] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 15:52:50,890] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 15:52:50,894] INFO in app: System encoding: utf-8
[2025-08-03 15:52:50,899] INFO in app: ==================================================
[2025-08-03 16:10:05,505] INFO in app: ==================================================
[2025-08-03 16:10:05,513] INFO in app: Application logging initialized successfully
[2025-08-03 16:10:05,517] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 16:10:05,519] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 16:10:05,523] INFO in app: System encoding: utf-8
[2025-08-03 16:10:05,526] INFO in app: ==================================================
[2025-08-03 16:20:26,288] INFO in app: ==================================================
[2025-08-03 16:20:26,297] INFO in app: Application logging initialized successfully
[2025-08-03 16:20:26,300] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 16:20:26,302] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 16:20:26,310] INFO in app: System encoding: utf-8
[2025-08-03 16:20:26,316] INFO in app: ==================================================
[2025-08-03 18:58:10,247] INFO in app: ==================================================
[2025-08-03 18:58:10,256] INFO in app: Application logging initialized successfully
[2025-08-03 18:58:10,258] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 18:58:10,259] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 18:58:10,261] INFO in app: System encoding: utf-8
[2025-08-03 18:58:10,264] INFO in app: ==================================================
[2025-08-03 18:58:19,585] INFO in app: ==================================================
[2025-08-03 18:58:19,590] INFO in app: Application logging initialized successfully
[2025-08-03 18:58:19,593] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 18:58:19,594] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 18:58:19,600] INFO in app: System encoding: utf-8
[2025-08-03 18:58:19,602] INFO in app: ==================================================
[2025-08-03 19:07:24,366] INFO in app: ==================================================
[2025-08-03 19:07:24,430] INFO in app: Application logging initialized successfully
[2025-08-03 19:07:24,432] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 19:07:24,433] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 19:07:24,435] INFO in app: System encoding: utf-8
[2025-08-03 19:07:24,436] INFO in app: ==================================================
[2025-08-03 19:13:38,452] INFO in app: ==================================================
[2025-08-03 19:13:38,458] INFO in app: Application logging initialized successfully
[2025-08-03 19:13:38,460] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 19:13:38,462] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 19:13:38,464] INFO in app: System encoding: utf-8
[2025-08-03 19:13:38,467] INFO in app: ==================================================
[2025-08-03 19:15:42,168] INFO in app: ==================================================
[2025-08-03 19:15:42,174] INFO in app: Application logging initialized successfully
[2025-08-03 19:15:42,176] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 19:15:42,178] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 19:15:42,183] INFO in app: System encoding: utf-8
[2025-08-03 19:15:42,185] INFO in app: ==================================================
[2025-08-03 19:23:28,921] INFO in app: ==================================================
[2025-08-03 19:23:28,929] INFO in app: Application logging initialized successfully
[2025-08-03 19:23:28,949] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 19:23:28,951] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 19:23:28,958] INFO in app: System encoding: utf-8
[2025-08-03 19:23:28,961] INFO in app: ==================================================
[2025-08-03 19:25:56,880] INFO in app: ==================================================
[2025-08-03 19:25:56,886] INFO in app: Application logging initialized successfully
[2025-08-03 19:25:56,889] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 19:25:56,890] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 19:25:56,895] INFO in app: System encoding: utf-8
[2025-08-03 19:25:56,898] INFO in app: ==================================================
[2025-08-03 19:26:19,551] INFO in app: ==================================================
[2025-08-03 19:26:19,557] INFO in app: Application logging initialized successfully
[2025-08-03 19:26:19,560] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 19:26:19,561] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 19:26:19,564] INFO in app: System encoding: utf-8
[2025-08-03 19:26:19,565] INFO in app: ==================================================
[2025-08-03 19:26:39,831] INFO in app: ==================================================
[2025-08-03 19:26:39,837] INFO in app: Application logging initialized successfully
[2025-08-03 19:26:39,840] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 19:26:39,842] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 19:26:39,845] INFO in app: System encoding: utf-8
[2025-08-03 19:26:39,846] INFO in app: ==================================================
[2025-08-03 19:29:50,433] INFO in app: ==================================================
[2025-08-03 19:29:50,444] INFO in app: Application logging initialized successfully
[2025-08-03 19:29:50,448] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 19:29:50,452] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 19:29:50,454] INFO in app: System encoding: utf-8
[2025-08-03 19:29:50,456] INFO in app: ==================================================
[2025-08-03 19:34:50,371] INFO in app: ==================================================
[2025-08-03 19:34:50,378] INFO in app: Application logging initialized successfully
[2025-08-03 19:34:50,380] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 19:34:50,381] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 19:34:50,383] INFO in app: System encoding: utf-8
[2025-08-03 19:34:50,385] INFO in app: ==================================================
[2025-08-03 19:59:24,398] INFO in app: ==================================================
[2025-08-03 19:59:24,405] INFO in app: Application logging initialized successfully
[2025-08-03 19:59:24,410] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 19:59:24,412] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 19:59:24,414] INFO in app: System encoding: utf-8
[2025-08-03 19:59:24,416] INFO in app: ==================================================
[2025-08-03 20:02:10,944] INFO in app: ==================================================
[2025-08-03 20:02:10,951] INFO in app: Application logging initialized successfully
[2025-08-03 20:02:10,954] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:02:10,955] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:02:10,957] INFO in app: System encoding: utf-8
[2025-08-03 20:02:10,959] INFO in app: ==================================================
[2025-08-03 20:06:11,191] INFO in app: ==================================================
[2025-08-03 20:06:11,197] INFO in app: Application logging initialized successfully
[2025-08-03 20:06:11,199] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:06:11,201] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:06:11,203] INFO in app: System encoding: utf-8
[2025-08-03 20:06:11,208] INFO in app: ==================================================
[2025-08-03 20:21:35,807] INFO in app: ==================================================
[2025-08-03 20:21:35,823] INFO in app: Application logging initialized successfully
[2025-08-03 20:21:35,829] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:21:35,831] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:21:35,834] INFO in app: System encoding: utf-8
[2025-08-03 20:21:35,838] INFO in app: ==================================================
[2025-08-03 20:22:30,471] INFO in app: ==================================================
[2025-08-03 20:22:30,479] INFO in app: Application logging initialized successfully
[2025-08-03 20:22:30,481] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:22:30,483] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:22:30,485] INFO in app: System encoding: utf-8
[2025-08-03 20:22:30,492] INFO in app: ==================================================
[2025-08-03 20:24:28,207] INFO in app: ==================================================
[2025-08-03 20:24:28,216] INFO in app: Application logging initialized successfully
[2025-08-03 20:24:28,219] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:24:28,220] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:24:28,224] INFO in app: System encoding: utf-8
[2025-08-03 20:24:28,227] INFO in app: ==================================================
[2025-08-03 20:24:38,952] INFO in app: ==================================================
[2025-08-03 20:24:38,959] INFO in app: Application logging initialized successfully
[2025-08-03 20:24:38,961] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:24:38,963] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:24:38,967] INFO in app: System encoding: utf-8
[2025-08-03 20:24:38,971] INFO in app: ==================================================
[2025-08-03 20:24:43,834] INFO in app: ==================================================
[2025-08-03 20:24:43,839] INFO in app: Application logging initialized successfully
[2025-08-03 20:24:43,841] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:24:43,843] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:24:43,846] INFO in app: System encoding: utf-8
[2025-08-03 20:24:43,852] INFO in app: ==================================================
[2025-08-03 20:42:04,985] INFO in app: ==================================================
[2025-08-03 20:42:04,996] INFO in app: Application logging initialized successfully
[2025-08-03 20:42:04,998] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:42:05,000] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:42:05,003] INFO in app: System encoding: utf-8
[2025-08-03 20:42:05,005] INFO in app: ==================================================
[2025-08-03 20:43:08,973] INFO in app: ==================================================
[2025-08-03 20:43:08,991] INFO in app: Application logging initialized successfully
[2025-08-03 20:43:08,995] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:43:08,998] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:43:09,000] INFO in app: System encoding: utf-8
[2025-08-03 20:43:09,006] INFO in app: ==================================================
[2025-08-03 20:44:09,219] INFO in app: ==================================================
[2025-08-03 20:44:09,305] INFO in app: Application logging initialized successfully
[2025-08-03 20:44:09,308] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:44:09,309] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:44:09,310] INFO in app: System encoding: utf-8
[2025-08-03 20:44:09,312] INFO in app: ==================================================
[2025-08-03 20:44:09,365] INFO in app: ==================================================
[2025-08-03 20:44:09,365] INFO in app: ==================================================
[2025-08-03 20:44:09,370] INFO in app: Application logging initialized successfully
[2025-08-03 20:44:09,370] INFO in app: Application logging initialized successfully
[2025-08-03 20:44:09,372] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:44:09,372] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:44:09,375] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:44:09,375] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:44:09,378] INFO in app: System encoding: utf-8
[2025-08-03 20:44:09,378] INFO in app: System encoding: utf-8
[2025-08-03 20:44:09,380] INFO in app: ==================================================
[2025-08-03 20:44:09,380] INFO in app: ==================================================
[2025-08-03 20:50:11,743] INFO in app: ==================================================
[2025-08-03 20:50:11,756] INFO in app: Application logging initialized successfully
[2025-08-03 20:50:11,765] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:50:11,767] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:50:11,769] INFO in app: System encoding: utf-8
[2025-08-03 20:50:11,771] INFO in app: ==================================================
[2025-08-03 20:57:12,927] INFO in app: ==================================================
[2025-08-03 20:57:12,935] INFO in app: Application logging initialized successfully
[2025-08-03 20:57:12,945] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 20:57:12,947] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 20:57:12,953] INFO in app: System encoding: utf-8
[2025-08-03 20:57:12,956] INFO in app: ==================================================
[2025-08-03 20:57:17,750] ERROR in app: Database error in get_sales_data: 'total_days'
[2025-08-03 20:57:17,751] WARNING in app: Sending email with fallback sales data
[2025-08-03 20:57:17,753] ERROR in app: Failed to send email: email/sales_report.html
[2025-08-03 21:08:28,997] INFO in app: ==================================================
[2025-08-03 21:08:29,007] INFO in app: Application logging initialized successfully
[2025-08-03 21:08:29,009] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 21:08:29,011] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 21:08:29,012] INFO in app: System encoding: utf-8
[2025-08-03 21:08:29,015] INFO in app: ==================================================
[2025-08-03 21:30:31,296] INFO in app: ==================================================
[2025-08-03 21:30:31,302] INFO in app: Application logging initialized successfully
[2025-08-03 21:30:31,304] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 21:30:31,306] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 21:30:31,311] INFO in app: System encoding: utf-8
[2025-08-03 21:30:31,313] INFO in app: ==================================================
[2025-08-03 21:31:00,735] INFO in app: ==================================================
[2025-08-03 21:31:00,743] INFO in app: Application logging initialized successfully
[2025-08-03 21:31:00,746] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 21:31:00,749] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 21:31:00,754] INFO in app: System encoding: utf-8
[2025-08-03 21:31:00,757] INFO in app: ==================================================
[2025-08-03 21:31:11,946] INFO in app: ==================================================
[2025-08-03 21:31:11,954] INFO in app: Application logging initialized successfully
[2025-08-03 21:31:11,957] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 21:31:11,961] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 21:31:11,966] INFO in app: System encoding: utf-8
[2025-08-03 21:31:11,968] INFO in app: ==================================================
[2025-08-03 21:31:18,734] INFO in app: ==================================================
[2025-08-03 21:31:18,743] INFO in app: Application logging initialized successfully
[2025-08-03 21:31:18,746] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 21:31:18,748] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 21:31:18,752] INFO in app: System encoding: utf-8
[2025-08-03 21:31:18,754] INFO in app: ==================================================
[2025-08-03 21:31:24,710] INFO in app: ==================================================
[2025-08-03 21:31:24,718] INFO in app: Application logging initialized successfully
[2025-08-03 21:31:24,723] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-03 21:31:24,729] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-03 21:31:24,731] INFO in app: System encoding: utf-8
[2025-08-03 21:31:24,733] INFO in app: ==================================================
[2025-08-03 21:31:39,758] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-04 09:05:02,064] INFO in app: ==================================================
[2025-08-04 09:05:02,151] INFO in app: Application logging initialized successfully
[2025-08-04 09:05:02,153] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-04 09:05:02,154] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-04 09:05:02,156] INFO in app: System encoding: utf-8
[2025-08-04 09:05:02,160] INFO in app: ==================================================
[2025-08-04 19:59:10,758] INFO in app: ==================================================
[2025-08-04 19:59:10,885] INFO in app: Application logging initialized successfully
[2025-08-04 19:59:10,890] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-04 19:59:10,892] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-04 19:59:10,900] INFO in app: System encoding: utf-8
[2025-08-04 19:59:10,912] INFO in app: ==================================================
[2025-08-04 19:59:31,759] ERROR in app: Email failed: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) database is locked
[SQL: INSERT INTO notifications (recipient_id, email_recipients, email_subject, email_content, email_sent, sent_at, message, type, is_read, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (None, 'alfred@kwachafinancialservices.com,sales@yourcompany.mw', 'Sales Report August 04, 2025', 'Automated sales report', 0, None, 'Sales report dispatched', 'report', 0, '2025-08-04 17:59:26.250174')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-08-04 19:59:45,621] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 03:14:09,181] INFO in app: ==================================================
[2025-08-05 03:14:09,262] INFO in app: Application logging initialized successfully
[2025-08-05 03:14:09,264] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 03:14:09,265] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 03:14:09,267] INFO in app: System encoding: utf-8
[2025-08-05 03:14:09,270] INFO in app: ==================================================
[2025-08-05 03:14:28,628] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 03:14:33,305] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 03:24:38,361] INFO in app: ==================================================
[2025-08-05 03:24:38,368] INFO in app: Application logging initialized successfully
[2025-08-05 03:24:38,370] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 03:24:38,371] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 03:24:38,374] INFO in app: System encoding: utf-8
[2025-08-05 03:24:38,376] INFO in app: ==================================================
[2025-08-05 03:24:58,071] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 03:29:19,560] INFO in app: ==================================================
[2025-08-05 03:29:19,566] INFO in app: Application logging initialized successfully
[2025-08-05 03:29:19,569] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 03:29:19,571] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 03:29:19,574] INFO in app: System encoding: utf-8
[2025-08-05 03:29:19,576] INFO in app: ==================================================
[2025-08-05 03:29:42,167] ERROR in app: Email failed: 'notif' is undefined
[2025-08-05 03:35:35,541] INFO in app: ==================================================
[2025-08-05 03:35:35,548] INFO in app: Application logging initialized successfully
[2025-08-05 03:35:35,550] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 03:35:35,552] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 03:35:35,555] INFO in app: System encoding: utf-8
[2025-08-05 03:35:35,556] INFO in app: ==================================================
[2025-08-05 03:35:45,422] ERROR in app: Email failed: 'notif' is undefined
[2025-08-05 03:41:51,369] INFO in app: ==================================================
[2025-08-05 03:41:51,380] INFO in app: Application logging initialized successfully
[2025-08-05 03:41:51,384] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 03:41:51,392] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 03:41:51,395] INFO in app: System encoding: utf-8
[2025-08-05 03:41:51,397] INFO in app: ==================================================
[2025-08-05 03:42:02,883] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 03:43:29,225] INFO in app: ==================================================
[2025-08-05 03:43:29,232] INFO in app: Application logging initialized successfully
[2025-08-05 03:43:29,234] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 03:43:29,236] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 03:43:29,238] INFO in app: System encoding: utf-8
[2025-08-05 03:43:29,240] INFO in app: ==================================================
[2025-08-05 03:43:42,499] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 03:59:07,752] INFO in app: ==================================================
[2025-08-05 03:59:07,759] INFO in app: Application logging initialized successfully
[2025-08-05 03:59:07,761] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 03:59:07,763] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 03:59:07,765] INFO in app: System encoding: utf-8
[2025-08-05 03:59:07,767] INFO in app: ==================================================
[2025-08-05 03:59:20,666] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 04:24:29,693] INFO in app: ==================================================
[2025-08-05 04:24:29,700] INFO in app: Application logging initialized successfully
[2025-08-05 04:24:29,704] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 04:24:29,706] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 04:24:29,710] INFO in app: System encoding: utf-8
[2025-08-05 04:24:29,712] INFO in app: ==================================================
[2025-08-05 04:24:45,961] ERROR in app: Exception on /admin/dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 2894, in admin_dashboard
    form=form,
         ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
[2025-08-05 04:25:24,058] INFO in app: ==================================================
[2025-08-05 04:25:24,069] INFO in app: Application logging initialized successfully
[2025-08-05 04:25:24,072] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 04:25:24,077] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 04:25:24,080] INFO in app: System encoding: utf-8
[2025-08-05 04:25:24,086] INFO in app: ==================================================
[2025-08-05 04:25:26,806] ERROR in app: Exception on /admin/dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 2894, in admin_dashboard
    recent_recipients=recent_recipients,
                      ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'recent_recipients' where it is not associated with a value
[2025-08-05 04:34:56,320] INFO in app: ==================================================
[2025-08-05 04:34:56,329] INFO in app: Application logging initialized successfully
[2025-08-05 04:34:56,333] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 04:34:56,336] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 04:34:56,342] INFO in app: System encoding: utf-8
[2025-08-05 04:34:56,345] INFO in app: ==================================================
[2025-08-05 04:35:03,135] ERROR in app: Exception on /admin/dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 2906, in admin_dashboard
    recent_recipients=recent_recipients,
                      ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'recent_recipients' where it is not associated with a value
[2025-08-05 04:36:22,412] INFO in app: ==================================================
[2025-08-05 04:36:22,420] INFO in app: Application logging initialized successfully
[2025-08-05 04:36:22,423] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 04:36:22,427] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 04:36:22,432] INFO in app: System encoding: utf-8
[2025-08-05 04:36:22,434] INFO in app: ==================================================
[2025-08-05 04:44:53,599] INFO in app: ==================================================
[2025-08-05 04:44:53,609] INFO in app: Application logging initialized successfully
[2025-08-05 04:44:53,612] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 04:44:53,614] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 04:44:53,617] INFO in app: System encoding: utf-8
[2025-08-05 04:44:53,624] INFO in app: ==================================================
[2025-08-05 04:45:47,674] ERROR in app: Sales data error: 'start_of_last_month'
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\app.py", line 8075, in get_sales_data
    last_month_sales = get_mtd_sales(comparisons['start_of_last_month'], comparisons['last_month_days'])
                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'start_of_last_month'
[2025-08-05 04:45:50,409] ERROR in app: Sales data error: 'start_of_last_month'
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\app.py", line 8075, in get_sales_data
    last_month_sales = get_mtd_sales(comparisons['start_of_last_month'], comparisons['last_month_days'])
                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'start_of_last_month'
[2025-08-05 04:45:52,935] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 04:45:53,462] ERROR in app: Sales data error: 'start_of_last_month'
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\app.py", line 8075, in get_sales_data
    last_month_sales = get_mtd_sales(comparisons['start_of_last_month'], comparisons['last_month_days'])
                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'start_of_last_month'
[2025-08-05 04:45:57,728] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 04:45:58,635] ERROR in app: Sales data error: 'start_of_last_month'
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\app.py", line 8075, in get_sales_data
    last_month_sales = get_mtd_sales(comparisons['start_of_last_month'], comparisons['last_month_days'])
                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'start_of_last_month'
[2025-08-05 04:46:00,127] ERROR in app: Sales data error: 'start_of_last_month'
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\app.py", line 8075, in get_sales_data
    last_month_sales = get_mtd_sales(comparisons['start_of_last_month'], comparisons['last_month_days'])
                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'start_of_last_month'
[2025-08-05 04:46:02,483] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 04:46:03,372] ERROR in app: Sales data error: 'start_of_last_month'
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\app.py", line 8075, in get_sales_data
    last_month_sales = get_mtd_sales(comparisons['start_of_last_month'], comparisons['last_month_days'])
                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'start_of_last_month'
[2025-08-05 04:46:05,739] ERROR in app: Email failed: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) database is locked
[SQL: INSERT INTO notifications (recipient_id, email_recipients, email_subject, email_content, email_sent, sent_at, message, type, is_read, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (None, 'alfred@kwachafinancialservices.com,sales@yourcompany.mw', 'Sales Report August 05, 2025', 'We are here!', 0, None, 'Sales report dispatched', 'report', 0, '2025-08-05 02:46:00.135571')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-08-05 04:46:07,386] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 04:46:11,758] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 04:47:39,481] ERROR in app: Sales data error: 'start_of_last_month'
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\app.py", line 8075, in get_sales_data
    last_month_sales = get_mtd_sales(comparisons['start_of_last_month'], comparisons['last_month_days'])
                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'start_of_last_month'
[2025-08-05 04:47:43,875] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 04:51:18,800] INFO in app: ==================================================
[2025-08-05 04:51:18,807] INFO in app: Application logging initialized successfully
[2025-08-05 04:51:18,809] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 04:51:18,810] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 04:51:18,812] INFO in app: System encoding: utf-8
[2025-08-05 04:51:18,814] INFO in app: ==================================================
[2025-08-05 04:51:49,090] ERROR in app: Sales data error: 'start_of_last_month'
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\app.py", line 8075, in get_sales_data
    last_month_sales = get_mtd_sales(comparisons['start_of_last_month'], comparisons['last_month_days'])
                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'start_of_last_month'
[2025-08-05 04:51:53,677] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 04:54:35,277] INFO in app: ==================================================
[2025-08-05 04:54:35,290] INFO in app: Application logging initialized successfully
[2025-08-05 04:54:35,296] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 04:54:35,299] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 04:54:35,302] INFO in app: System encoding: utf-8
[2025-08-05 04:54:35,304] INFO in app: ==================================================
[2025-08-05 04:55:25,817] ERROR in app: Exception on /admin/dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 2909, in admin_dashboard
    return render_template(
        'admin_dashboard.html',
    ...<7 lines>...
        terms=[]
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\pc\loan-app\templates\admin_dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\pc\loan-app\templates\base.html", line 177, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\templates\admin_dashboard.html", line 267, in block 'content'
    {{ form.hidden_tag() }}
    ^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
[2025-08-05 05:00:11,630] INFO in app: ==================================================
[2025-08-05 05:00:11,637] INFO in app: Application logging initialized successfully
[2025-08-05 05:00:11,640] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 05:00:11,644] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 05:00:11,650] INFO in app: System encoding: utf-8
[2025-08-05 05:00:11,652] INFO in app: ==================================================
[2025-08-05 05:00:26,345] ERROR in app: Exception on /admin/dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 2909, in admin_dashboard
    return render_template(
        'admin_dashboard.html',
    ...<7 lines>...
        terms=[]
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\pc\loan-app\templates\admin_dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\pc\loan-app\templates\base.html", line 177, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\templates\admin_dashboard.html", line 267, in block 'content'
    {{ form.hidden_tag() }}
    ^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
[2025-08-05 05:00:28,463] ERROR in app: Exception on /admin/dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 2909, in admin_dashboard
    return render_template(
        'admin_dashboard.html',
    ...<7 lines>...
        terms=[]
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\pc\loan-app\templates\admin_dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\pc\loan-app\templates\base.html", line 177, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\templates\admin_dashboard.html", line 267, in block 'content'
    {{ form.hidden_tag() }}
    ^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
[2025-08-05 05:00:47,330] INFO in app: ==================================================
[2025-08-05 05:00:47,337] INFO in app: Application logging initialized successfully
[2025-08-05 05:00:47,339] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 05:00:47,341] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 05:00:47,343] INFO in app: System encoding: utf-8
[2025-08-05 05:00:47,345] INFO in app: ==================================================
[2025-08-05 05:01:19,983] ERROR in app: Sales data error: 'start_of_last_month'
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\app.py", line 8080, in get_sales_data
    last_month_sales = get_mtd_sales(comparisons['start_of_last_month'], comparisons['last_month_days'])
                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'start_of_last_month'
[2025-08-05 05:01:26,454] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 05:01:41,396] ERROR in app: Exception on /admin/dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 2909, in admin_dashboard
    return render_template(
        'admin_dashboard.html',
    ...<7 lines>...
        terms=[]
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\pc\loan-app\templates\admin_dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\pc\loan-app\templates\base.html", line 177, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\templates\admin_dashboard.html", line 267, in block 'content'
    {{ form.hidden_tag() }}
    ^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
[2025-08-05 05:10:07,152] INFO in app: ==================================================
[2025-08-05 05:10:07,176] INFO in app: Application logging initialized successfully
[2025-08-05 05:10:07,198] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 05:10:07,203] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 05:10:07,219] INFO in app: System encoding: utf-8
[2025-08-05 05:10:07,226] INFO in app: ==================================================
[2025-08-05 05:11:04,488] INFO in app: ==================================================
[2025-08-05 05:11:04,517] INFO in app: Application logging initialized successfully
[2025-08-05 05:11:04,524] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 05:11:04,529] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 05:11:04,533] INFO in app: System encoding: utf-8
[2025-08-05 05:11:04,535] INFO in app: ==================================================
[2025-08-05 05:24:09,830] INFO in app: ==================================================
[2025-08-05 05:24:09,838] INFO in app: Application logging initialized successfully
[2025-08-05 05:24:09,842] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 05:24:09,844] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 05:24:09,847] INFO in app: System encoding: utf-8
[2025-08-05 05:24:09,851] INFO in app: ==================================================
[2025-08-05 05:24:20,656] ERROR in app: Exception on /admin/dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 2870, in admin_dashboard
    form.emails.data = last_notification.email_recipients
    ^^^^
NameError: name 'form' is not defined. Did you mean: 'format'?
[2025-08-05 05:25:20,296] INFO in app: ==================================================
[2025-08-05 05:25:20,305] INFO in app: Application logging initialized successfully
[2025-08-05 05:25:20,312] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 05:25:20,318] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 05:25:20,320] INFO in app: System encoding: utf-8
[2025-08-05 05:25:20,323] INFO in app: ==================================================
[2025-08-05 05:25:26,107] ERROR in app: Exception on /admin/dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 2893, in admin_dashboard
    return render_template(
        'admin_dashboard.html',
    ...<8 lines>...
        recent_recipients=recent_recipients
    )
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\pc\loan-app\templates\admin_dashboard.html", line 308, in template
    {% elif section == 'votes' %}
    ^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'elif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
[2025-08-05 05:26:16,365] INFO in app: ==================================================
[2025-08-05 05:26:16,371] INFO in app: Application logging initialized successfully
[2025-08-05 05:26:16,373] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 05:26:16,375] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 05:26:16,378] INFO in app: System encoding: utf-8
[2025-08-05 05:26:16,382] INFO in app: ==================================================
[2025-08-05 05:28:35,444] ERROR in app: Sales data error: 'start_of_last_month'
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\app.py", line 8082, in get_sales_data
    last_month_sales = get_mtd_sales(comparisons['start_of_last_month'], comparisons['last_month_days'])
                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'start_of_last_month'
[2025-08-05 05:28:39,895] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 05:39:12,545] INFO in app: ==================================================
[2025-08-05 05:39:12,552] INFO in app: Application logging initialized successfully
[2025-08-05 05:39:12,556] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 05:39:12,559] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 05:39:12,565] INFO in app: System encoding: utf-8
[2025-08-05 05:39:12,567] INFO in app: ==================================================
[2025-08-05 05:39:30,395] INFO in app: Sending email to: alfred@kwachafinancialservices.com, alfieka08@yahoo.com, info@kwachafinancialservices.com
[2025-08-05 05:39:30,397] ERROR in app: Exception on /admin/dashboard [POST]
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\loan-app\app.py", line 2878, in admin_dashboard
    success = send_sales_notification_email(
        recipients=recipients,
        custom_message=form.message.data,
        subject=form.subject.data
    )
TypeError: send_sales_notification_email() got an unexpected keyword argument 'subject'
[2025-08-05 05:41:19,970] INFO in app: ==================================================
[2025-08-05 05:41:19,978] INFO in app: Application logging initialized successfully
[2025-08-05 05:41:19,980] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 05:41:19,982] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 05:41:19,985] INFO in app: System encoding: utf-8
[2025-08-05 05:41:19,992] INFO in app: ==================================================
[2025-08-05 05:42:37,652] INFO in app: Sending email to: alfred@kwachafinancialservices.com, alfieka08@yahoo.com, info@kwachafinancialservices.com
[2025-08-05 05:42:37,659] ERROR in app: Sales data error: 'start_of_last_month'
Traceback (most recent call last):
  File "C:\Users\pc\loan-app\app.py", line 8079, in get_sales_data
    last_month_sales = get_mtd_sales(comparisons['start_of_last_month'], comparisons['last_month_days'])
                                     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'start_of_last_month'
[2025-08-05 05:42:42,434] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'alfieka08@yahoo.com', 'info@kwachafinancialservices.com']
[2025-08-05 05:56:31,760] INFO in app: ==================================================
[2025-08-05 05:56:31,769] INFO in app: Application logging initialized successfully
[2025-08-05 05:56:31,772] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 05:56:31,774] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 05:56:31,776] INFO in app: System encoding: utf-8
[2025-08-05 05:56:31,779] INFO in app: ==================================================
[2025-08-05 05:57:01,414] INFO in app: Sending email to: alfred@kwachafinancialservices.com, alfieka08@yahoo.com, info@kwachafinancialservices.com
[2025-08-05 05:57:06,871] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'alfieka08@yahoo.com', 'info@kwachafinancialservices.com']
[2025-08-05 06:00:17,358] INFO in app: Sending email to: alfred@kwachafinancialservices.com, alfieka08@yahoo.com, info@kwachafinancialservices.com
[2025-08-05 06:00:22,242] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'alfieka08@yahoo.com', 'info@kwachafinancialservices.com']
[2025-08-05 10:10:18,909] INFO in app: ==================================================
[2025-08-05 10:10:18,987] INFO in app: Application logging initialized successfully
[2025-08-05 10:10:18,988] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 10:10:18,989] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 10:10:18,991] INFO in app: System encoding: utf-8
[2025-08-05 10:10:18,992] INFO in app: ==================================================
[2025-08-05 10:18:39,810] INFO in app: ==================================================
[2025-08-05 10:18:39,828] INFO in app: Application logging initialized successfully
[2025-08-05 10:18:39,831] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 10:18:39,836] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 10:18:39,838] INFO in app: System encoding: utf-8
[2025-08-05 10:18:39,843] INFO in app: ==================================================
[2025-08-05 10:19:17,640] INFO in app: ==================================================
[2025-08-05 10:19:17,647] INFO in app: Application logging initialized successfully
[2025-08-05 10:19:17,649] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 10:19:17,650] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 10:19:17,658] INFO in app: System encoding: utf-8
[2025-08-05 10:19:17,660] INFO in app: ==================================================
[2025-08-05 10:32:11,195] INFO in app: ==================================================
[2025-08-05 10:32:11,204] INFO in app: Application logging initialized successfully
[2025-08-05 10:32:11,206] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 10:32:11,214] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 10:32:11,219] INFO in app: System encoding: utf-8
[2025-08-05 10:32:11,222] INFO in app: ==================================================
[2025-08-05 10:39:56,455] INFO in app: ==================================================
[2025-08-05 10:39:56,461] INFO in app: Application logging initialized successfully
[2025-08-05 10:39:56,463] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 10:39:56,465] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 10:39:56,472] INFO in app: System encoding: utf-8
[2025-08-05 10:39:56,474] INFO in app: ==================================================
[2025-08-05 10:59:13,202] INFO in app: ==================================================
[2025-08-05 10:59:13,209] INFO in app: Application logging initialized successfully
[2025-08-05 10:59:13,212] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 10:59:13,214] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 10:59:13,215] INFO in app: System encoding: utf-8
[2025-08-05 10:59:13,219] INFO in app: ==================================================
[2025-08-05 11:15:54,156] INFO in app: ==================================================
[2025-08-05 11:15:54,164] INFO in app: Application logging initialized successfully
[2025-08-05 11:15:54,166] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 11:15:54,171] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 11:15:54,175] INFO in app: System encoding: utf-8
[2025-08-05 11:15:54,178] INFO in app: ==================================================
[2025-08-05 11:17:07,967] INFO in app: ==================================================
[2025-08-05 11:17:07,973] INFO in app: Application logging initialized successfully
[2025-08-05 11:17:07,975] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 11:17:07,981] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 11:17:07,985] INFO in app: System encoding: utf-8
[2025-08-05 11:17:07,987] INFO in app: ==================================================
[2025-08-05 11:27:49,002] INFO in app: ==================================================
[2025-08-05 11:27:49,009] INFO in app: Application logging initialized successfully
[2025-08-05 11:27:49,014] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 11:27:49,016] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 11:27:49,021] INFO in app: System encoding: utf-8
[2025-08-05 11:27:49,022] INFO in app: ==================================================
[2025-08-05 11:28:04,164] INFO in app: ==================================================
[2025-08-05 11:28:04,174] INFO in app: Application logging initialized successfully
[2025-08-05 11:28:04,176] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 11:28:04,177] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 11:28:04,179] INFO in app: System encoding: utf-8
[2025-08-05 11:28:04,181] INFO in app: ==================================================
[2025-08-05 11:28:08,736] INFO in app: ==================================================
[2025-08-05 11:28:08,744] INFO in app: Application logging initialized successfully
[2025-08-05 11:28:08,746] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 11:28:08,749] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 11:28:08,751] INFO in app: System encoding: utf-8
[2025-08-05 11:28:08,758] INFO in app: ==================================================
[2025-08-05 11:48:16,116] INFO in app: ==================================================
[2025-08-05 11:48:16,124] INFO in app: Application logging initialized successfully
[2025-08-05 11:48:16,126] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 11:48:16,128] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 11:48:16,131] INFO in app: System encoding: utf-8
[2025-08-05 11:48:16,135] INFO in app: ==================================================
[2025-08-05 11:51:45,503] INFO in app: ==================================================
[2025-08-05 11:51:45,511] INFO in app: Application logging initialized successfully
[2025-08-05 11:51:45,514] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 11:51:45,517] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 11:51:45,518] INFO in app: System encoding: utf-8
[2025-08-05 11:51:45,522] INFO in app: ==================================================
[2025-08-05 11:51:55,511] INFO in app: ==================================================
[2025-08-05 11:51:55,517] INFO in app: Application logging initialized successfully
[2025-08-05 11:51:55,520] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 11:51:55,524] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 11:51:55,528] INFO in app: System encoding: utf-8
[2025-08-05 11:51:55,530] INFO in app: ==================================================
[2025-08-05 12:06:29,447] INFO in app: ==================================================
[2025-08-05 12:06:29,456] INFO in app: Application logging initialized successfully
[2025-08-05 12:06:29,463] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 12:06:29,468] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 12:06:29,471] INFO in app: System encoding: utf-8
[2025-08-05 12:06:29,474] INFO in app: ==================================================
[2025-08-05 12:07:38,281] INFO in app: ==================================================
[2025-08-05 12:07:38,289] INFO in app: Application logging initialized successfully
[2025-08-05 12:07:38,290] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 12:07:38,291] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 12:07:38,292] INFO in app: System encoding: utf-8
[2025-08-05 12:07:38,293] INFO in app: ==================================================
[2025-08-05 12:49:42,891] INFO in app: ==================================================
[2025-08-05 12:49:42,986] INFO in app: Application logging initialized successfully
[2025-08-05 12:49:42,989] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 12:49:42,992] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 12:49:42,995] INFO in app: System encoding: utf-8
[2025-08-05 12:49:42,999] INFO in app: ==================================================
[2025-08-05 13:00:20,075] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 13:16:27,961] INFO in app: HTML email sent to ['alfred@kwachafinancialservices.com', 'sales@yourcompany.mw']
[2025-08-05 14:37:48,109] INFO in app: ==================================================
[2025-08-05 14:37:48,225] INFO in app: Application logging initialized successfully
[2025-08-05 14:37:48,227] INFO in app: Log directory: C:\Users\pc\loan-app\logs
[2025-08-05 14:37:48,229] INFO in app: Python version: 3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]
[2025-08-05 14:37:48,234] INFO in app: System encoding: utf-8
[2025-08-05 14:37:48,236] INFO in app: ==================================================
